//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatformKit.Software.Internal.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlatformKit.Software.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package manager {x} is not installed on this device..
        /// </summary>
        internal static string Exceptions_PackageManagerNotInstalled {
            get {
                return ResourceManager.GetString("Exceptions.PackageManagerNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Package Manager &quot;{x}&quot; is not supported on this operating system..
        /// </summary>
        internal static string Exceptions_PackageManagerNotSupported {
            get {
                return ResourceManager.GetString("Exceptions.PackageManagerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is only supported on Linux, FreeBSD, and macOS. An attempt was made to run it on {x}..
        /// </summary>
        internal static string Exceptions_PlatformNotSupported_LinuxAndFreeBsdAndMacOnly {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.LinuxAndFreeBsdAndMacOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is only supported on Linux and FreeBSD. An attempt was made to run it on {x}..
        /// </summary>
        internal static string Exceptions_PlatformNotSupported_LinuxAndFreeBsdOnly {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.LinuxAndFreeBsdOnly", resourceCulture);
            }
        }
    }
}
